// Copyright © 2012-2020 VLINGO LABS. All rights reserved.
//
// This Source Code Form is subject to the terms of the
// Mozilla Public License, v. 2.0. If a copy of the MPL
// was not distributed with this file, You can obtain
// one at https://mozilla.org/MPL/2.0/.

namespace Vlingo.Xoom.Codegen.Template
{
    public enum Template
    {
        ANNOTATED_BOOTSTRAP,
        DEFAULT_BOOTSTRAP,
        AGGREGATE_PROTOCOL,
        AGGREGATE_PROTOCOL_INSTANCE_METHOD,
        AGGREGATE_PROTOCOL_STATIC_METHOD,
        AGGREGATE_STATE_METHOD,
        OBJECT_ENTITY,
        STATEFUL_ENTITY,
        STATEFUL_ENTITY_METHOD,
        EVENT_SOURCE_ENTITY,
        EVENT_SOURCE_ENTITY_METHOD,
        AGGREGATE_STATE,
        DOMAIN_EVENT,
        JOURNAL_PROVIDER,
        PERSISTENCE_SETUP,
        STATE_STORE_PROVIDER,
        OBJECT_STORE_PROVIDER,
        ENTRY_ADAPTER,
        STATE_ADAPTER,
        REST_RESOURCE,
        AUTO_DISPATCH_MAPPING,
        AUTO_DISPATCH_ROUTE,
        AUTO_DISPATCH_HANDLERS_MAPPING,
        AUTO_DISPATCH_HANDLER_ENTRY,
        XOOM_INITIALIZER,
        PROJECTION_DISPATCHER_PROVIDER,
        OPERATION_BASED_PROJECTION,
        EVENT_BASED_PROJECTION,
        DATA_OBJECT,
        PROJECTION_SOURCE_TYPES,
        DATABASE_PROPERTIES,
        QUERIES,
        REST_RESOURCE_CREATION_METHOD,
        REST_RESOURCE_RETRIEVE_METHOD,
        REST_RESOURCE_UPDATE_METHOD,
        QUERIES_ACTOR,
        CONSUMER_EXCHANGE_ADAPTER,
        PRODUCER_EXCHANGE_ADAPTER,
        EXCHANGE_RECEIVER_HOLDER,
        CONSUMER_EXCHANGE_MAPPER,
        PRODUCER_EXCHANGE_MAPPER,
        EXCHANGE_PROPERTIES,
        EXCHANGE_BOOTSTRAP,
        EXCHANGE_DISPATCHER,
        SCHEMATA_SPECIFICATION,
        SCHEMATA_PLUGIN
    }
}
