// Copyright © 2012-2022 VLINGO LABS. All rights reserved.
//
// This Source Code Form is subject to the terms of the
// Mozilla Public License, v. 2.0. If a copy of the MPL
// was not distributed with this file, You can obtain
// one at https://mozilla.org/MPL/2.0/.

namespace Vlingo.Xoom.Turbo.Codegen.Parameter
{
    public enum Label
    {
        Id,
        IdType,
        Body,
        BodyType,
        ApplicationName,
        Package,
        Aggregate,
        StateField,
        FieldType,
        DomainEvent,
        AggregateMethod,
        MethodParameter,
        FactoryMethod,
        RequireEntityLoading,
        StorageType,
        Cqrs,
        ProjectionType,
        Projectables,
        ProjectionActor,
        Source,
        Database,
        RestResources,
        MainClass,
        Deployment,
        AddressFactory,
        IdentityGenerator,
        BlockingMessaging,
        XoomInitializerName,
        CommandModelDatabase,
        QueryModelDatabase,
        GenerationLocation,
        AutoDispatchName,
        HandlersConfigName,
        ModelProtocol,
        ModelActor,
        ModelData,
        QueriesProtocol,
        QueriesActor,
        UriRoot,
        RouteSignature,
        RoutePath,
        RouteMethod,
        RouteHandlerInvocation,
        ReadOnly,
        UseCustomRouteHandlerParam,
        AdapterHandlerInvocation,
        UseCustomAdapterHandlerParam,
        UseAdapter,
        InternalRouteHandler,
        UseAnnotations,
        UseAutoDispatch,
        GroupId,
        ArtifactId,
        Version,
        XoomVersion,
        DockerImage,
        KubernetesImage,
        KubernetesPodName,
        TargetFolder,
        LocalType,
        Exchange,
        Schema,
        SchemaGroup,
        Receiver,
        ModelMethod,
        Role
    }
}
